version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      junit:
        patterns:
          - org.junit.jupiter:*
          - org.junit.platform:*
      kotest:
        patterns:
          - io.kotest:kotest-*
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
