name: CI Pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.provide_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build and check
        uses: christopherfrieler/gradle-wrapper-action@v0.6.0
        env:
          ORG_GRADLE_PROJECT_github_packages_user: ${{ github.actor }}
          ORG_GRADLE_PROJECT_github_packages_password: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: |
            check assemble generatePomFileForMavenPublication kotlinSourcesJar dokkaJavadocJar
            versionFile
          artifacts: |
            bq-connector-build kraftsql-bigquery/build/publications/maven/pom-default.xml kraftsql-bigquery/build/libs/kraftsql-bigquery-*.jar
            bq-testing-build kraftsql-bigquery-testing/build/publications/maven/pom-default.xml kraftsql-bigquery-testing/build/libs/kraftsql-bigquery-testing-*.jar
            bq-examples-test-report examples/build/reports/tests/test/**/*
      - id: provide_version
        run: echo "version=$(cat build/version.txt)" >> "$GITHUB_OUTPUT"

  deploy_snapshot:
    needs: ['build']
    if: github.ref_name == 'main' && endsWith(needs.build.outputs.version, '-SNAPSHOT')
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Deploy to Github Packages
        uses: christopherfrieler/gradle-wrapper-action@v0.6.0
        env:
          ORG_GRADLE_PROJECT_github_packages_user: ${{ github.actor }}
          ORG_GRADLE_PROJECT_github_packages_password: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_github_packages_publishing_user: ${{ github.actor }}
          ORG_GRADLE_PROJECT_github_packages_publishing_password: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: publishMavenPublicationToGitHubPackagesRepository
